export const ADMIN_EMAIL_TIPO_ENVIO = {
  COMUNICACION_LIBRE: "COMUNICACION_LIBRE",
  ASAMBLEA_CONVOCATORIA: "ASAMBLEA_CONVOCATORIA",
  ASAMBLEA_SIMULACION_ADMIN: "ASAMBLEA_SIMULACION_ADMIN",
} as const;

export const ASAMBLEA_TIPO = {
  ORDINARIA: "ORDINARIA",
  EXTRAORDINARIA: "EXTRAORDINARIA",
} as const;

export const ASAMBLEA_ESTADO = {
  BORRADOR: "BORRADOR",
  CONVOCADA: "CONVOCADA",
  REALIZADA: "REALIZADA",
  CERRADA: "CERRADA",
} as const;

export const ASAMBLEA_VOTACION_ESTADO = {
  BORRADOR: "BORRADOR",
  ABIERTA: "ABIERTA",
  CERRADA: "CERRADA",
} as const;

export const ASAMBLEA_VOTO_VALOR = {
  POSITIVO: "POSITIVO",
  NEGATIVO: "NEGATIVO",
} as const;
